


POST http://127.0.0.1:8080/auth/login
Content-Type: application/json

{
    "username": "jtorres990",
    "password": "123456"
}


###

POST http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
    "name": "julio", 
    "lastname": "torres",
    "username": "jtorres990",
    "password": "123456"
}


###

GET http://127.0.0.1:8080/auth/session?token=MTUxMTczMjE5NQgRmy1IPKG0EVhTSEq5HQa68xR7